--CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE usuario DROP COLUMN id CASCADE,
DROP COLUMN nome CASCADE,
DROP COLUMN enderecos CASCADE;

ALTER TABLE usuario 
ADD COLUMN id UUID PRIMARY KEY DEFAULT (uuidv7());